language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules

script:
    - npm run build
    - npm test

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build
on:
    branch: master